Fix terminal warnings and crosshair cursor after Image File is dragged into the canvas
akiraux/Akira pull request #591
Opened 2021-05-23 10:50 UTC by Abdallah-Moh

## Summary / How this PR fixes the problem?
This will deregister the insert mode after the canvas image has been created

## Steps to Test
Drag an Image File into the canvas

## Known Issues / Things To Do
No known issues

## This PR fixes/implements the following **bugs/features**:
Fix terminal warnings and crosshair cursor after Image File is dragged into the canvas

- Fixes Fix terminal warnings after Image File is dragged into the canvas
- Crosshair cursor after Image File is dragged into the canvas

2021-05-25 04:45 UTC, Alecaddd requested changes

2021-05-25 04:45 UTC, Alecaddd commented on src/Lib/Canvas.vala
> +        mode_manager.deregister_mode (Modes.InteractionMode.ModeType.ITEM_INSERT);
No need to specify the mode here as we can directly call `mode_manager.deregister_active_mode ();`

2021-05-25 04:51 UTC, Alecaddd commented
Since you're improving this area, there a bunch of other strange issues happening that you could investigate.

First, we could move the `window.event_bus.insert_item ("image");` outside the `foreach` loop since we don't need to re-set it for each image.

A couple of other problems appear when multiple images are dropped together.
1. Some images are not fully sized as they end up with 1px by 1px size.
2. Randomly, this error appears: `Gtk-WARNING **: 21:47:38.979: drawing failure for widget 'AkiraLibCanvas': invalid matrix (not invertible)` alongside others and the whole UI breaks.

I suspect there's a race issue with the generation of the pixbuf of each image.

2021-05-25 07:27 UTC, Abdallah-Moh commented
Can you please open an Issue or a discussion with more info and ping me

2021-05-25 07:37 UTC, Abdallah-Moh commented
I am currently investigating for the problem of the image with short height or short width
I did some investigation which lead me to know that when the height is shorter than the width and the width was resized to a number that made calculating the height a decimal which is less than 1 which in int gets converted to a 0 which breaks the whole app so I got an Idea before setting the pixpuf we will check if the calculated pixpuf height is less than a 1 then we set it to 1 and vice versa for the width

2021-05-26 02:22 UTC, Alecaddd commented on src/Lib/Canvas.vala
> +
You moved the method but you forgot the comment.
I'll fix this, but try to be more aware of the code around and the structure you're touching.

2021-05-26 02:24 UTC, merged